# Generated by Django 3.2.7 on 2021-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210928_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Максимальный объем встраиваемой памяти'),
        ),
    ]
